repetitions: 5

dataset_parameters:
  dataset    : 'MNIST'
  input_dim  : 784
  n_classes  : 10
  n_train    : 4000
  label_noise: 0.10

fcnn_parameters:
  hidden_nodes: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
                 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
                 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150]
  final_activation        : 'none'
  weight_reuse            : 'none'
  weight_initialization   : 'xavier_uniform'
  dropout                 : 0.0

training_parameters:
  loss                    : 'squared_loss'
  batch_size              : 128
  n_epochs                : 6000
  optimizer               : 'sgd'
  learning_rate           : 0.1
  weight_decay            : 0.0
  step_size_reduce_epochs : 500
  step_size_reduce_percent: 0.0
  stop_at_zero_error      : false
