repetitions: 5

dataset_parameters:
  dataset    : 'MNIST'
  input_dim  : 784
  n_classes  : 10
  n_train    : 10000
  label_noise: 0.10

rff_parameters:
  n_features: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]

training_parameters:
  regularization: 1e-6
